//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdiService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", ConfigurationName="OdiService.requestPortTypeCallback")]
    public interface requestPortTypeCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="xmlns.oracle.com/odi/OdiInvoke/invokeStartScenCallback")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task invokeStartScenCallbackAsync(OdiService.invokeStartScenCallback request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="xmlns.oracle.com/odi/OdiInvoke/invokeRestartSessCallback")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task invokeRestartSessCallbackAsync(OdiService.invokeRestartSessCallback request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiStartType
    {
        
        private long sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiMasterCredentialType
    {
        
        private string odiUserField;
        
        private string odiPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OdiUser
        {
            get
            {
                return this.odiUserField;
            }
            set
            {
                this.odiUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OdiPassword
        {
            get
            {
                return this.odiPasswordField;
            }
            set
            {
                this.odiPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class LoadPlanStatusType
    {
        
        private long loadPlanInstanceIdField;
        
        private long loadPlanRunNumberField;
        
        private string loadPlanStatusField;
        
        private string loadPlanReturnCodeField;
        
        private string loadPlanMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long LoadPlanInstanceId
        {
            get
            {
                return this.loadPlanInstanceIdField;
            }
            set
            {
                this.loadPlanInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long LoadPlanRunNumber
        {
            get
            {
                return this.loadPlanRunNumberField;
            }
            set
            {
                this.loadPlanRunNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LoadPlanStatus
        {
            get
            {
                return this.loadPlanStatusField;
            }
            set
            {
                this.loadPlanStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LoadPlanReturnCode
        {
            get
            {
                return this.loadPlanReturnCodeField;
            }
            set
            {
                this.loadPlanReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LoadPlanMessage
        {
            get
            {
                return this.loadPlanMessageField;
            }
            set
            {
                this.loadPlanMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class LoadPlanStatusRequestType
    {
        
        private long loadPlanInstanceIdField;
        
        private long loadPlanRunNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long LoadPlanInstanceId
        {
            get
            {
                return this.loadPlanInstanceIdField;
            }
            set
            {
                this.loadPlanInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long LoadPlanRunNumber
        {
            get
            {
                return this.loadPlanRunNumberField;
            }
            set
            {
                this.loadPlanRunNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class odiRestartLoadPlanType
    {
        
        private OdiLoadPlanInstanceRunInformationType startedRunInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OdiLoadPlanInstanceRunInformationType StartedRunInformation
        {
            get
            {
                return this.startedRunInformationField;
            }
            set
            {
                this.startedRunInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiLoadPlanInstanceRunInformationType
    {
        
        private long odiLoadPlanInstanceIdField;
        
        private long runCountField;
        
        private int masterRepositoryIdField;
        
        private string masterRepositoryTimestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long OdiLoadPlanInstanceId
        {
            get
            {
                return this.odiLoadPlanInstanceIdField;
            }
            set
            {
                this.odiLoadPlanInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long RunCount
        {
            get
            {
                return this.runCountField;
            }
            set
            {
                this.runCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int MasterRepositoryId
        {
            get
            {
                return this.masterRepositoryIdField;
            }
            set
            {
                this.masterRepositoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MasterRepositoryTimestamp
        {
            get
            {
                return this.masterRepositoryTimestampField;
            }
            set
            {
                this.masterRepositoryTimestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class RestartLoadPlanRequestType
    {
        
        private long loadPlanInstanceIdField;
        
        private int logLevelField;
        
        private bool logLevelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long LoadPlanInstanceId
        {
            get
            {
                return this.loadPlanInstanceIdField;
            }
            set
            {
                this.loadPlanInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int LogLevel
        {
            get
            {
                return this.logLevelField;
            }
            set
            {
                this.logLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LogLevelSpecified
        {
            get
            {
                return this.logLevelFieldSpecified;
            }
            set
            {
                this.logLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiStopLoadPlanType
    {
        
        private OdiLoadPlanInstanceRunInformationType stoppedRunInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OdiLoadPlanInstanceRunInformationType StoppedRunInformation
        {
            get
            {
                return this.stoppedRunInformationField;
            }
            set
            {
                this.stoppedRunInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class StopLoadPlanRequestType
    {
        
        private long loadPlanInstanceIdField;
        
        private long loadPlanInstanceRunCountField;
        
        private string stopLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long LoadPlanInstanceId
        {
            get
            {
                return this.loadPlanInstanceIdField;
            }
            set
            {
                this.loadPlanInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long LoadPlanInstanceRunCount
        {
            get
            {
                return this.loadPlanInstanceRunCountField;
            }
            set
            {
                this.loadPlanInstanceRunCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string StopLevel
        {
            get
            {
                return this.stopLevelField;
            }
            set
            {
                this.stopLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiStartLoadPlanType
    {
        
        private OdiLoadPlanInstanceRunInformationType startedRunInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OdiLoadPlanInstanceRunInformationType StartedRunInformation
        {
            get
            {
                return this.startedRunInformationField;
            }
            set
            {
                this.startedRunInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class StartLoadPlanRequestType
    {
        
        private string loadPlanNameField;
        
        private string contextField;
        
        private string keywordsField;
        
        private int logLevelField;
        
        private bool logLevelFieldSpecified;
        
        private VariableType[] loadPlanStartupParametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LoadPlanName
        {
            get
            {
                return this.loadPlanNameField;
            }
            set
            {
                this.loadPlanNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Keywords
        {
            get
            {
                return this.keywordsField;
            }
            set
            {
                this.keywordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int LogLevel
        {
            get
            {
                return this.logLevelField;
            }
            set
            {
                this.logLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LogLevelSpecified
        {
            get
            {
                return this.logLevelFieldSpecified;
            }
            set
            {
                this.logLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LoadPlanStartupParameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public VariableType[] LoadPlanStartupParameters
        {
            get
            {
                return this.loadPlanStartupParametersField;
            }
            set
            {
                this.loadPlanStartupParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class VariableType
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class SessionStatusType
    {
        
        private long sessionIdField;
        
        private string sessionStatusField;
        
        private string sessionReturnCodeField;
        
        private string sessionMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long SessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SessionStatus
        {
            get
            {
                return this.sessionStatusField;
            }
            set
            {
                this.sessionStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SessionReturnCode
        {
            get
            {
                return this.sessionReturnCodeField;
            }
            set
            {
                this.sessionReturnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SessionMessage
        {
            get
            {
                return this.sessionMessageField;
            }
            set
            {
                this.sessionMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class SessionRequestType
    {
        
        private bool synchronousField;
        
        private long sessionIdField;
        
        private bool keepVariablesField;
        
        private int logLevelField;
        
        private bool logLevelFieldSpecified;
        
        private VariableType[] variablesField;
        
        public SessionRequestType()
        {
            this.synchronousField = true;
            this.keepVariablesField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Synchronous
        {
            get
            {
                return this.synchronousField;
            }
            set
            {
                this.synchronousField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long SessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool KeepVariables
        {
            get
            {
                return this.keepVariablesField;
            }
            set
            {
                this.keepVariablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int LogLevel
        {
            get
            {
                return this.logLevelField;
            }
            set
            {
                this.logLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LogLevelSpecified
        {
            get
            {
                return this.logLevelFieldSpecified;
            }
            set
            {
                this.logLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Variables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public VariableType[] Variables
        {
            get
            {
                return this.variablesField;
            }
            set
            {
                this.variablesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class DebugType
    {
        
        private bool debugField;
        
        private bool suspendOnFirstStepField;
        
        private bool debugDescendantsField;
        
        private bool breakOnErrorField;
        
        public DebugType()
        {
            this.debugField = false;
            this.suspendOnFirstStepField = true;
            this.debugDescendantsField = false;
            this.breakOnErrorField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Debug
        {
            get
            {
                return this.debugField;
            }
            set
            {
                this.debugField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool SuspendOnFirstStep
        {
            get
            {
                return this.suspendOnFirstStepField;
            }
            set
            {
                this.suspendOnFirstStepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DebugDescendants
        {
            get
            {
                return this.debugDescendantsField;
            }
            set
            {
                this.debugDescendantsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool BreakOnError
        {
            get
            {
                return this.breakOnErrorField;
            }
            set
            {
                this.breakOnErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class ScenarioRequestType
    {
        
        private string scenarioNameField;
        
        private string scenarioVersionField;
        
        private string contextField;
        
        private bool synchronousField;
        
        private string sessionNameField;
        
        private string keywordsField;
        
        private VariableType[] variablesField;
        
        private int logLevelField;
        
        public ScenarioRequestType()
        {
            this.synchronousField = true;
            this.logLevelField = 5;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ScenarioName
        {
            get
            {
                return this.scenarioNameField;
            }
            set
            {
                this.scenarioNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ScenarioVersion
        {
            get
            {
                return this.scenarioVersionField;
            }
            set
            {
                this.scenarioVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Synchronous
        {
            get
            {
                return this.synchronousField;
            }
            set
            {
                this.synchronousField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SessionName
        {
            get
            {
                return this.sessionNameField;
            }
            set
            {
                this.sessionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Keywords
        {
            get
            {
                return this.keywordsField;
            }
            set
            {
                this.keywordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Variables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public VariableType[] Variables
        {
            get
            {
                return this.variablesField;
            }
            set
            {
                this.variablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.ComponentModel.DefaultValueAttribute(5)]
        public int LogLevel
        {
            get
            {
                return this.logLevelField;
            }
            set
            {
                this.logLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiCredentialType
    {
        
        private string odiUserField;
        
        private string odiPasswordField;
        
        private string workRepositoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OdiUser
        {
            get
            {
                return this.odiUserField;
            }
            set
            {
                this.odiUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OdiPassword
        {
            get
            {
                return this.odiPasswordField;
            }
            set
            {
                this.odiPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WorkRepository
        {
            get
            {
                return this.workRepositoryField;
            }
            set
            {
                this.workRepositoryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeStartScenCallback
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiStartType OdiStartScenResponse;
        
        public invokeStartScenCallback()
        {
        }
        
        public invokeStartScenCallback(OdiService.OdiStartType OdiStartScenResponse)
        {
            this.OdiStartScenResponse = OdiStartScenResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeRestartSessCallback
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiStartType OdiRestartSessResponse;
        
        public invokeRestartSessCallback()
        {
        }
        
        public invokeRestartSessCallback(OdiService.OdiStartType OdiRestartSessResponse)
        {
            this.OdiRestartSessResponse = OdiRestartSessResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface requestPortTypeCallbackChannel : OdiService.requestPortTypeCallback, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class requestPortTypeCallbackClient : System.ServiceModel.ClientBase<OdiService.requestPortTypeCallback>, OdiService.requestPortTypeCallback
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public requestPortTypeCallbackClient() : 
                base(requestPortTypeCallbackClient.GetDefaultBinding(), requestPortTypeCallbackClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OdiInvokeCallbackSOAP11Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public requestPortTypeCallbackClient(EndpointConfiguration endpointConfiguration) : 
                base(requestPortTypeCallbackClient.GetBindingForEndpoint(endpointConfiguration), requestPortTypeCallbackClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public requestPortTypeCallbackClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(requestPortTypeCallbackClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public requestPortTypeCallbackClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(requestPortTypeCallbackClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public requestPortTypeCallbackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task OdiService.requestPortTypeCallback.invokeStartScenCallbackAsync(OdiService.invokeStartScenCallback request)
        {
            return base.Channel.invokeStartScenCallbackAsync(request);
        }
        
        public System.Threading.Tasks.Task invokeStartScenCallbackAsync(OdiService.OdiStartType OdiStartScenResponse)
        {
            OdiService.invokeStartScenCallback inValue = new OdiService.invokeStartScenCallback();
            inValue.OdiStartScenResponse = OdiStartScenResponse;
            return ((OdiService.requestPortTypeCallback)(this)).invokeStartScenCallbackAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task OdiService.requestPortTypeCallback.invokeRestartSessCallbackAsync(OdiService.invokeRestartSessCallback request)
        {
            return base.Channel.invokeRestartSessCallbackAsync(request);
        }
        
        public System.Threading.Tasks.Task invokeRestartSessCallbackAsync(OdiService.OdiStartType OdiRestartSessResponse)
        {
            OdiService.invokeRestartSessCallback inValue = new OdiService.invokeRestartSessCallback();
            inValue.OdiRestartSessResponse = OdiRestartSessResponse;
            return ((OdiService.requestPortTypeCallback)(this)).invokeRestartSessCallbackAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OdiInvokeCallbackSOAP11Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OdiInvokeCallbackSOAP11Port))
            {
                return new System.ServiceModel.EndpointAddress("http://set.by.caller/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return requestPortTypeCallbackClient.GetBindingForEndpoint(EndpointConfiguration.OdiInvokeCallbackSOAP11Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return requestPortTypeCallbackClient.GetEndpointAddress(EndpointConfiguration.OdiInvokeCallbackSOAP11Port);
        }
        
        public enum EndpointConfiguration
        {
            
            OdiInvokeCallbackSOAP11Port,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", ConfigurationName="OdiService.requestPortType")]
    public interface requestPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="xmlns.oracle.com/odi/OdiInvoke/invokeStartScen", ReplyAction="xmlns.oracle.com/odi/OdiInvoke/requestPortType/invokeStartScenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OdiService.invokeStartScenResponse> invokeStartScenAsync(OdiService.invokeStartScenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="xmlns.oracle.com/odi/OdiInvoke/invokeStartScenWithCallback")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task invokeStartScenWithCallbackAsync(OdiService.invokeStartScenWithCallback request);
        
        [System.ServiceModel.OperationContractAttribute(Action="xmlns.oracle.com/odi/OdiInvoke/getVersion", ReplyAction="xmlns.oracle.com/odi/OdiInvoke/requestPortType/getVersionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OdiService.getVersionResponse> getVersionAsync(OdiService.getVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="xmlns.oracle.com/odi/OdiInvoke/invokeRestartSess", ReplyAction="xmlns.oracle.com/odi/OdiInvoke/requestPortType/invokeRestartSessResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OdiService.invokeRestartSessResponse> invokeRestartSessAsync(OdiService.invokeRestartSessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="xmlns.oracle.com/odi/OdiInvoke/invokeRestartSessWithCallback")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task invokeRestartSessWithCallbackAsync(OdiService.invokeRestartSessWithCallback request);
        
        [System.ServiceModel.OperationContractAttribute(Action="xmlns.oracle.com/odi/OdiInvoke/getSessionStatus", ReplyAction="xmlns.oracle.com/odi/OdiInvoke/requestPortType/getSessionStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OdiService.getSessionStatusResponse> getSessionStatusAsync(OdiService.getSessionStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="xmlns.oracle.com/odi/OdiInvoke/invokeStartLoadPlan", ReplyAction="xmlns.oracle.com/odi/OdiInvoke/requestPortType/invokeStartLoadPlanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OdiService.invokeStartLoadPlanResponse> invokeStartLoadPlanAsync(OdiService.invokeStartLoadPlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="xmlns.oracle.com/odi/OdiInvoke/invokeStopLoadPlan", ReplyAction="xmlns.oracle.com/odi/OdiInvoke/requestPortType/invokeStopLoadPlanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OdiService.invokeStopLoadPlanResponse> invokeStopLoadPlanAsync(OdiService.invokeStopLoadPlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="xmlns.oracle.com/odi/OdiInvoke/invokeRestartLoadPlan", ReplyAction="xmlns.oracle.com/odi/OdiInvoke/requestPortType/invokeRestartLoadPlanResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OdiService.invokeRestartLoadPlanResponse> invokeRestartLoadPlanAsync(OdiService.invokeRestartLoadPlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="xmlns.oracle.com/odi/OdiInvoke/getLoadPlanStatus", ReplyAction="xmlns.oracle.com/odi/OdiInvoke/requestPortType/getLoadPlanStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OdiService.getLoadPlanStatusResponse> getLoadPlanStatusAsync(OdiService.getLoadPlanStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="xmlns.oracle.com/odi/OdiInvoke/refreshAgentConfig", ReplyAction="xmlns.oracle.com/odi/OdiInvoke/requestPortType/refreshAgentConfigResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OdiService.refreshAgentConfigResponse> refreshAgentConfigAsync(OdiService.refreshAgentConfigRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiStartScenRequest
    {
        
        private OdiCredentialType credentialsField;
        
        private ScenarioRequestType requestField;
        
        private DebugType debugField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdiCredentialType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ScenarioRequestType Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DebugType Debug
        {
            get
            {
                return this.debugField;
            }
            set
            {
                this.debugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeStartScenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiStartScenRequest OdiStartScenRequest;
        
        public invokeStartScenRequest()
        {
        }
        
        public invokeStartScenRequest(OdiService.OdiStartScenRequest OdiStartScenRequest)
        {
            this.OdiStartScenRequest = OdiStartScenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeStartScenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiStartType OdiStartScenResponse;
        
        public invokeStartScenResponse()
        {
        }
        
        public invokeStartScenResponse(OdiService.OdiStartType OdiStartScenResponse)
        {
            this.OdiStartScenResponse = OdiStartScenResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiStartScenWithCallbackRequest
    {
        
        private OdiCredentialType credentialsField;
        
        private ScenarioRequestType requestField;
        
        private DebugType debugField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdiCredentialType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ScenarioRequestType Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DebugType Debug
        {
            get
            {
                return this.debugField;
            }
            set
            {
                this.debugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeStartScenWithCallback
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiStartScenWithCallbackRequest OdiStartScenWithCallbackRequest;
        
        public invokeStartScenWithCallback()
        {
        }
        
        public invokeStartScenWithCallback(OdiService.OdiStartScenWithCallbackRequest OdiStartScenWithCallbackRequest)
        {
            this.OdiStartScenWithCallbackRequest = OdiStartScenWithCallbackRequest;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class getWebServiceVersionRequest
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class getWebServiceVersionResponse
    {
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.getWebServiceVersionRequest getWebServiceVersionRequest;
        
        public getVersionRequest()
        {
        }
        
        public getVersionRequest(OdiService.getWebServiceVersionRequest getWebServiceVersionRequest)
        {
            this.getWebServiceVersionRequest = getWebServiceVersionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.getWebServiceVersionResponse getWebServiceVersionResponse;
        
        public getVersionResponse()
        {
        }
        
        public getVersionResponse(OdiService.getWebServiceVersionResponse getWebServiceVersionResponse)
        {
            this.getWebServiceVersionResponse = getWebServiceVersionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiRestartSessRequest
    {
        
        private OdiCredentialType credentialsField;
        
        private SessionRequestType requestField;
        
        private DebugType debugField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdiCredentialType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SessionRequestType Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DebugType Debug
        {
            get
            {
                return this.debugField;
            }
            set
            {
                this.debugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeRestartSessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiRestartSessRequest OdiRestartSessRequest;
        
        public invokeRestartSessRequest()
        {
        }
        
        public invokeRestartSessRequest(OdiService.OdiRestartSessRequest OdiRestartSessRequest)
        {
            this.OdiRestartSessRequest = OdiRestartSessRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeRestartSessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiStartType OdiRestartSessResponse;
        
        public invokeRestartSessResponse()
        {
        }
        
        public invokeRestartSessResponse(OdiService.OdiStartType OdiRestartSessResponse)
        {
            this.OdiRestartSessResponse = OdiRestartSessResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiRestartSessWithCallbackRequest
    {
        
        private OdiCredentialType credentialsField;
        
        private SessionRequestType requestField;
        
        private DebugType debugField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdiCredentialType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SessionRequestType Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DebugType Debug
        {
            get
            {
                return this.debugField;
            }
            set
            {
                this.debugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeRestartSessWithCallback
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiRestartSessWithCallbackRequest OdiRestartSessWithCallbackRequest;
        
        public invokeRestartSessWithCallback()
        {
        }
        
        public invokeRestartSessWithCallback(OdiService.OdiRestartSessWithCallbackRequest OdiRestartSessWithCallbackRequest)
        {
            this.OdiRestartSessWithCallbackRequest = OdiRestartSessWithCallbackRequest;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiGetSessionsStatusRequest
    {
        
        private OdiCredentialType credentialsField;
        
        private long[] sessionIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OdiCredentialType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SessionIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long[] SessionIds
        {
            get
            {
                return this.sessionIdsField;
            }
            set
            {
                this.sessionIdsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSessionStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiGetSessionsStatusRequest OdiGetSessionsStatusRequest;
        
        public getSessionStatusRequest()
        {
        }
        
        public getSessionStatusRequest(OdiService.OdiGetSessionsStatusRequest OdiGetSessionsStatusRequest)
        {
            this.OdiGetSessionsStatusRequest = OdiGetSessionsStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSessionStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SessionStatusResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public OdiService.SessionStatusType[] OdiGetSessionsStatusResponse;
        
        public getSessionStatusResponse()
        {
        }
        
        public getSessionStatusResponse(OdiService.SessionStatusType[] OdiGetSessionsStatusResponse)
        {
            this.OdiGetSessionsStatusResponse = OdiGetSessionsStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiStartLoadPlanRequest
    {
        
        private OdiCredentialType credentialsField;
        
        private StartLoadPlanRequestType startLoadPlanRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdiCredentialType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StartLoadPlanRequestType StartLoadPlanRequest
        {
            get
            {
                return this.startLoadPlanRequestField;
            }
            set
            {
                this.startLoadPlanRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiStartLoadPlanResponse
    {
        
        private OdiStartLoadPlanType executionInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OdiStartLoadPlanType executionInfo
        {
            get
            {
                return this.executionInfoField;
            }
            set
            {
                this.executionInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeStartLoadPlanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiStartLoadPlanRequest OdiStartLoadPlanRequest;
        
        public invokeStartLoadPlanRequest()
        {
        }
        
        public invokeStartLoadPlanRequest(OdiService.OdiStartLoadPlanRequest OdiStartLoadPlanRequest)
        {
            this.OdiStartLoadPlanRequest = OdiStartLoadPlanRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeStartLoadPlanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiStartLoadPlanResponse OdiStartLoadPlanResponse;
        
        public invokeStartLoadPlanResponse()
        {
        }
        
        public invokeStartLoadPlanResponse(OdiService.OdiStartLoadPlanResponse OdiStartLoadPlanResponse)
        {
            this.OdiStartLoadPlanResponse = OdiStartLoadPlanResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiStopLoadPlanRequest
    {
        
        private OdiCredentialType credentialsField;
        
        private StopLoadPlanRequestType odiStopLoadPlanRequest1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdiCredentialType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OdiStopLoadPlanRequest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StopLoadPlanRequestType OdiStopLoadPlanRequest1
        {
            get
            {
                return this.odiStopLoadPlanRequest1Field;
            }
            set
            {
                this.odiStopLoadPlanRequest1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiStopLoadPlanResponse
    {
        
        private OdiStopLoadPlanType executionInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OdiStopLoadPlanType executionInfo
        {
            get
            {
                return this.executionInfoField;
            }
            set
            {
                this.executionInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeStopLoadPlanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiStopLoadPlanRequest OdiStopLoadPlanRequest;
        
        public invokeStopLoadPlanRequest()
        {
        }
        
        public invokeStopLoadPlanRequest(OdiService.OdiStopLoadPlanRequest OdiStopLoadPlanRequest)
        {
            this.OdiStopLoadPlanRequest = OdiStopLoadPlanRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeStopLoadPlanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiStopLoadPlanResponse OdiStopLoadPlanResponse;
        
        public invokeStopLoadPlanResponse()
        {
        }
        
        public invokeStopLoadPlanResponse(OdiService.OdiStopLoadPlanResponse OdiStopLoadPlanResponse)
        {
            this.OdiStopLoadPlanResponse = OdiStopLoadPlanResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiRestartLoadPlanRequest
    {
        
        private OdiCredentialType credentialsField;
        
        private RestartLoadPlanRequestType restartLoadPlanRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OdiCredentialType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public RestartLoadPlanRequestType RestartLoadPlanRequest
        {
            get
            {
                return this.restartLoadPlanRequestField;
            }
            set
            {
                this.restartLoadPlanRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiRestartLoadPlanResponse
    {
        
        private odiRestartLoadPlanType executionInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public odiRestartLoadPlanType executionInfo
        {
            get
            {
                return this.executionInfoField;
            }
            set
            {
                this.executionInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeRestartLoadPlanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiRestartLoadPlanRequest OdiRestartLoadPlanRequest;
        
        public invokeRestartLoadPlanRequest()
        {
        }
        
        public invokeRestartLoadPlanRequest(OdiService.OdiRestartLoadPlanRequest OdiRestartLoadPlanRequest)
        {
            this.OdiRestartLoadPlanRequest = OdiRestartLoadPlanRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeRestartLoadPlanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiRestartLoadPlanResponse OdiRestartLoadPlanResponse;
        
        public invokeRestartLoadPlanResponse()
        {
        }
        
        public invokeRestartLoadPlanResponse(OdiService.OdiRestartLoadPlanResponse OdiRestartLoadPlanResponse)
        {
            this.OdiRestartLoadPlanResponse = OdiRestartLoadPlanResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiGetLoadPlanStatusRequest
    {
        
        private OdiCredentialType credentialsField;
        
        private LoadPlanStatusRequestType[] loadPlansField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OdiCredentialType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LoadPlans", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public LoadPlanStatusRequestType[] LoadPlans
        {
            get
            {
                return this.loadPlansField;
            }
            set
            {
                this.loadPlansField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLoadPlanStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiGetLoadPlanStatusRequest OdiGetLoadPlanStatusRequest;
        
        public getLoadPlanStatusRequest()
        {
        }
        
        public getLoadPlanStatusRequest(OdiService.OdiGetLoadPlanStatusRequest OdiGetLoadPlanStatusRequest)
        {
            this.OdiGetLoadPlanStatusRequest = OdiGetLoadPlanStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLoadPlanStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LoadPlanStatusResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public OdiService.LoadPlanStatusType[] OdiGetLoadPlanStatusResponse;
        
        public getLoadPlanStatusResponse()
        {
        }
        
        public getLoadPlanStatusResponse(OdiService.LoadPlanStatusType[] OdiGetLoadPlanStatusResponse)
        {
            this.OdiGetLoadPlanStatusResponse = OdiGetLoadPlanStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xmlns.oracle.com/odi/OdiInvoke/")]
    public partial class OdiRefreshAgentConfigRequest
    {
        
        private OdiMasterCredentialType credentialsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OdiMasterCredentialType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class refreshAgentConfigRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public OdiService.OdiRefreshAgentConfigRequest OdiRefreshAgentConfigRequest;
        
        public refreshAgentConfigRequest()
        {
        }
        
        public refreshAgentConfigRequest(OdiService.OdiRefreshAgentConfigRequest OdiRefreshAgentConfigRequest)
        {
            this.OdiRefreshAgentConfigRequest = OdiRefreshAgentConfigRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class refreshAgentConfigResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="xmlns.oracle.com/odi/OdiInvoke/", Order=0)]
        public string OdiRefreshAgentConfigResponse;
        
        public refreshAgentConfigResponse()
        {
        }
        
        public refreshAgentConfigResponse(string OdiRefreshAgentConfigResponse)
        {
            this.OdiRefreshAgentConfigResponse = OdiRefreshAgentConfigResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface requestPortTypeChannel : OdiService.requestPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class requestPortTypeClient : System.ServiceModel.ClientBase<OdiService.requestPortType>, OdiService.requestPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public requestPortTypeClient() : 
                base(requestPortTypeClient.GetDefaultBinding(), requestPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OdiInvokeRequestSOAP11port0.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public requestPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(requestPortTypeClient.GetBindingForEndpoint(endpointConfiguration), requestPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public requestPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(requestPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public requestPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(requestPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public requestPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdiService.invokeStartScenResponse> OdiService.requestPortType.invokeStartScenAsync(OdiService.invokeStartScenRequest request)
        {
            return base.Channel.invokeStartScenAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdiService.invokeStartScenResponse> invokeStartScenAsync(OdiService.OdiStartScenRequest OdiStartScenRequest)
        {
            OdiService.invokeStartScenRequest inValue = new OdiService.invokeStartScenRequest();
            inValue.OdiStartScenRequest = OdiStartScenRequest;
            return ((OdiService.requestPortType)(this)).invokeStartScenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task OdiService.requestPortType.invokeStartScenWithCallbackAsync(OdiService.invokeStartScenWithCallback request)
        {
            return base.Channel.invokeStartScenWithCallbackAsync(request);
        }
        
        public System.Threading.Tasks.Task invokeStartScenWithCallbackAsync(OdiService.OdiStartScenWithCallbackRequest OdiStartScenWithCallbackRequest)
        {
            OdiService.invokeStartScenWithCallback inValue = new OdiService.invokeStartScenWithCallback();
            inValue.OdiStartScenWithCallbackRequest = OdiStartScenWithCallbackRequest;
            return ((OdiService.requestPortType)(this)).invokeStartScenWithCallbackAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdiService.getVersionResponse> OdiService.requestPortType.getVersionAsync(OdiService.getVersionRequest request)
        {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdiService.getVersionResponse> getVersionAsync(OdiService.getWebServiceVersionRequest getWebServiceVersionRequest)
        {
            OdiService.getVersionRequest inValue = new OdiService.getVersionRequest();
            inValue.getWebServiceVersionRequest = getWebServiceVersionRequest;
            return ((OdiService.requestPortType)(this)).getVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdiService.invokeRestartSessResponse> OdiService.requestPortType.invokeRestartSessAsync(OdiService.invokeRestartSessRequest request)
        {
            return base.Channel.invokeRestartSessAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdiService.invokeRestartSessResponse> invokeRestartSessAsync(OdiService.OdiRestartSessRequest OdiRestartSessRequest)
        {
            OdiService.invokeRestartSessRequest inValue = new OdiService.invokeRestartSessRequest();
            inValue.OdiRestartSessRequest = OdiRestartSessRequest;
            return ((OdiService.requestPortType)(this)).invokeRestartSessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task OdiService.requestPortType.invokeRestartSessWithCallbackAsync(OdiService.invokeRestartSessWithCallback request)
        {
            return base.Channel.invokeRestartSessWithCallbackAsync(request);
        }
        
        public System.Threading.Tasks.Task invokeRestartSessWithCallbackAsync(OdiService.OdiRestartSessWithCallbackRequest OdiRestartSessWithCallbackRequest)
        {
            OdiService.invokeRestartSessWithCallback inValue = new OdiService.invokeRestartSessWithCallback();
            inValue.OdiRestartSessWithCallbackRequest = OdiRestartSessWithCallbackRequest;
            return ((OdiService.requestPortType)(this)).invokeRestartSessWithCallbackAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdiService.getSessionStatusResponse> OdiService.requestPortType.getSessionStatusAsync(OdiService.getSessionStatusRequest request)
        {
            return base.Channel.getSessionStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdiService.getSessionStatusResponse> getSessionStatusAsync(OdiService.OdiGetSessionsStatusRequest OdiGetSessionsStatusRequest)
        {
            OdiService.getSessionStatusRequest inValue = new OdiService.getSessionStatusRequest();
            inValue.OdiGetSessionsStatusRequest = OdiGetSessionsStatusRequest;
            return ((OdiService.requestPortType)(this)).getSessionStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdiService.invokeStartLoadPlanResponse> OdiService.requestPortType.invokeStartLoadPlanAsync(OdiService.invokeStartLoadPlanRequest request)
        {
            return base.Channel.invokeStartLoadPlanAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdiService.invokeStartLoadPlanResponse> invokeStartLoadPlanAsync(OdiService.OdiStartLoadPlanRequest OdiStartLoadPlanRequest)
        {
            OdiService.invokeStartLoadPlanRequest inValue = new OdiService.invokeStartLoadPlanRequest();
            inValue.OdiStartLoadPlanRequest = OdiStartLoadPlanRequest;
            return ((OdiService.requestPortType)(this)).invokeStartLoadPlanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdiService.invokeStopLoadPlanResponse> OdiService.requestPortType.invokeStopLoadPlanAsync(OdiService.invokeStopLoadPlanRequest request)
        {
            return base.Channel.invokeStopLoadPlanAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdiService.invokeStopLoadPlanResponse> invokeStopLoadPlanAsync(OdiService.OdiStopLoadPlanRequest OdiStopLoadPlanRequest)
        {
            OdiService.invokeStopLoadPlanRequest inValue = new OdiService.invokeStopLoadPlanRequest();
            inValue.OdiStopLoadPlanRequest = OdiStopLoadPlanRequest;
            return ((OdiService.requestPortType)(this)).invokeStopLoadPlanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdiService.invokeRestartLoadPlanResponse> OdiService.requestPortType.invokeRestartLoadPlanAsync(OdiService.invokeRestartLoadPlanRequest request)
        {
            return base.Channel.invokeRestartLoadPlanAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdiService.invokeRestartLoadPlanResponse> invokeRestartLoadPlanAsync(OdiService.OdiRestartLoadPlanRequest OdiRestartLoadPlanRequest)
        {
            OdiService.invokeRestartLoadPlanRequest inValue = new OdiService.invokeRestartLoadPlanRequest();
            inValue.OdiRestartLoadPlanRequest = OdiRestartLoadPlanRequest;
            return ((OdiService.requestPortType)(this)).invokeRestartLoadPlanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdiService.getLoadPlanStatusResponse> OdiService.requestPortType.getLoadPlanStatusAsync(OdiService.getLoadPlanStatusRequest request)
        {
            return base.Channel.getLoadPlanStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdiService.getLoadPlanStatusResponse> getLoadPlanStatusAsync(OdiService.OdiGetLoadPlanStatusRequest OdiGetLoadPlanStatusRequest)
        {
            OdiService.getLoadPlanStatusRequest inValue = new OdiService.getLoadPlanStatusRequest();
            inValue.OdiGetLoadPlanStatusRequest = OdiGetLoadPlanStatusRequest;
            return ((OdiService.requestPortType)(this)).getLoadPlanStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OdiService.refreshAgentConfigResponse> OdiService.requestPortType.refreshAgentConfigAsync(OdiService.refreshAgentConfigRequest request)
        {
            return base.Channel.refreshAgentConfigAsync(request);
        }
        
        public System.Threading.Tasks.Task<OdiService.refreshAgentConfigResponse> refreshAgentConfigAsync(OdiService.OdiRefreshAgentConfigRequest OdiRefreshAgentConfigRequest)
        {
            OdiService.refreshAgentConfigRequest inValue = new OdiService.refreshAgentConfigRequest();
            inValue.OdiRefreshAgentConfigRequest = OdiRefreshAgentConfigRequest;
            return ((OdiService.requestPortType)(this)).refreshAgentConfigAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OdiInvokeRequestSOAP11port0))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OdiInvokeRequestSOAP11port0))
            {
                return new System.ServiceModel.EndpointAddress("http://odi-assur1-dev.claro.com.co:8100/oraclediagent-Assurance/OdiInvoke");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return requestPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.OdiInvokeRequestSOAP11port0);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return requestPortTypeClient.GetEndpointAddress(EndpointConfiguration.OdiInvokeRequestSOAP11port0);
        }
        
        public enum EndpointConfiguration
        {
            
            OdiInvokeRequestSOAP11port0,
        }
    }
}
